name: Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  jobs:
    run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repos
      uses: actions/checkout@v3
      
    - name: Set up node.js
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    
    - name: Install node.js dependencies
      run: pnpm install
    
    - name: Run linters
      run: pnpm run lint
    
    - name: Compile latest release 
      run: git tag v1.1.0
      
    - name: Pushing tags
      run: git push --tags
      
